version: "3.9"

x-uffizzi:
  ingress:
    service: app
    port: 8000

services:
  app:
    build: https://github.com/fedorov-dualboot/container-restart
    ports:
      - "8000:8000"
    restart: always
